[package]
name = "server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.4.2"
prost = "0.7.0"
tonic-reflection = "0.1.0"
# Required for wellknown types
prost-types = "0.7"
# asyncio runtime requirements
tokio = { version = "1.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tokio-stream = { version =  "0.1", features = ["net"] }

[build-dependencies]
tonic-build = "0.4.2"
